language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "sudo apt-get install python-numpy python-scipy -qq"
  - "pip install flask flask-login scikit-learn"
# command to run tests
script: python -m unittest discover
